### ISSUE TITLE
'Array of' handling 

### ISSUE THREAD

**Issue by Regloom** [sapmentors/cds-pg#104]
Hi team,

First of all thank you for your hard work. 
Recently I came across an issue with 'Array of' handling for PostgreeSQL.

Here is my DB schema:
`entity Settings {
  key id: Integer;
  tempThreshold: Decimal(3,1) not null; 
  notifications: array of {
   description: String;
    frequency: Integer enum {
      daily = 1;
      weekly = 2;
      monthly = 3;
    };
    message: String;
  }
}`

Which is projected as follows: `entity Settings as projection on db.Settings ;`

Here is the created **Settings** table after executing `npx cds-dbm deploy --create-db`  :
![Settings](https://user-images.githubusercontent.com/2860671/112107828-7fdb6b00-8bc0-11eb-89f1-53b17b28ba23.JPG)

CSV upload works fine and uploads data to the database, here is a sample CSV:

_id;tempThreshold;notifications
1;36.8;[{"description": "samle notification","frequency": 2,"message": "Please mail us ASAP"}]_

However oData services methods GET/POST doesn't work and return the following error:
`"error": {
    "code": "500",
    "message": "Serialization Error: Value of collection property 'notifications' must be an array."
}`

This is of course a very rare case when array is present in db schema but might be a subject for future development.

p.s. Sample JSON payload for POST:

POST {{server}}/Settings
Content-Type: application/json;charset=UTF-8;IEEE754Compatible=true

{
  "id": 2,
  "tempThreshold": "10.1",
  "notifications": [{
    "description": "New settings",
    "frequency": 1,
    "message": "String"
  }]
}

Best regards,
Egor

**Comment by vobu** [comment]
hi, thanks for the detailed issue report!
and given that CAP encourages domain-driven modelling (just like what you did with
```js
notifications: array of { 
  description: String; 
  frequency: Integer enum { 
    daily = 1; 
    weekly = 2; 
    monthly = 3; 
  }
}
```
instead of putting this in a relation e.g. via `association of`),
i think it's not just a rare case, but a pending issue we need to address.

could you bake a test case into code?

i would see the cds-runtime/-ql related test in https://github.com/sapmentors/cds-pg/blob/main/__tests__/lib/pg/ql.test.js
where you could load a dedicated model à la (watch out, pidgeon code)
```js
  test('load array model prop', async () => {
       await deploy(yourModel, {}).to(this._dbProperties)
      
     const { Setting } = cds.entities('your.name.space')

      const setting = await cds.run(INSERT.into(...).entries([{ 
        "id": 2,
        "tempThreshold": "10.1",
         "notifications": [{
             "description": "New settings",
             "frequency": 1,
              "message": "String"
          }] 
      }]

      expect(setting.affectedRows).toStrictEqual(1)

      const singleSetting = await cds.run(SELECT.one(Setting).where({ id: '2 }))
      expect(singleSetting).toHaveProperty('notifications', ...)
    })
```

and the related OData-related test (`POST` with payload) in https://github.com/sapmentors/cds-pg/blob/main/__tests__/lib/pg/service.test.js 
- could deploy your custom model similar to https://github.com/sapmentors/cds-pg/blob/36918827f2e072ae1ec8f26ae3d5964dc705a3de/__tests__/lib/pg/service.test.js#L77
- select your inserted data similar to https://github.com/sapmentors/cds-pg/blob/36918827f2e072ae1ec8f26ae3d5964dc705a3de/__tests__/lib/pg/service.test.js#L105

this would make it way easier to both locate the origin of the bug and be closer to the domain-modelling idea of CAP also with PostgreSQL!

**Comment by Regloom** [comment]
Ok looks like I've managed the first part. 

```
test('load array model prop', async () => {
      await deploy('./arraymodel.cds', {}).to(this._dbProperties)
      const { Settings } = cds.entities('arraymodel')
 
      const setting = await cds.run(INSERT.into(Settings).entries([{ 
         "id": 2,
         "tempThreshold": "10.1",
         "notifications": [{
              "description": "New settings",
              "frequency": 1,
               "message": "String"
         }] 
       }]))
 
       expect(setting.affectedRows).toStrictEqual(1)
 
       const singleSetting = await cds.run(SELECT.one(Settings).where({ id: 2 }))
       expect(singleSetting).toHaveProperty('notifications', '[{"description": "New settings","frequency": 1,"message": "String"}]')
     })
```

here is a content of arraymodel.cds file:
```
namespace arraymodel;

service settingsService {
    entity Settings {
        key id: Integer;
        tempThreshold: Decimal(3,1) not null;
        Notifications: Array of {
            description: String;
            frequency: Integer enum {
                daily = 1;
                weekly = 2;
                monthly = 3;
            };
            message: String;
        }
    }
}
```
I'm new to the JS testing frameworks, so I might misunderstand the process (

**Comment by vobu** [comment]
cool, things start coming together!
the test looks fine!
hint 1: use `test.only` to ... well ... only run that one test when you issue `npm run test -- <testfilename>`
hint 2: please find much more detail about the test- and dev-env setup in https://github.com/sapmentors/cds-pg/blob/main/docs/CONTRIBUTING.md#runnable-queries-and-runtime-debug-capabilites

looking fwd to the odata-level test, then we have something to work in the `array of` feature in postgres!
