### ISSUE TITLE
Make cds deploy work

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cds-pg#39]
When running:

`cds deploy`

currently the error message:

`[ERROR] Didn't find a deployer module for 'PostgreSQL'`

is returned. Let's find out what we need to implement to implement to use this instead of the `cds-pg deploy` command.

**Comment by mikezaschka** [comment]
Taken from `@sap/cds-dk/bin/deploy/index.js`:

```Javascript
try {
    var deployer = require ('./to-'+kind)
  } catch (e) {
    if (e.code === 'MODULE_NOT_FOUND') {
      throw new Error(`Didn't find a deployer module for '${kind}'`)
    }
  }
```
Only local deployers within the `@sap/cds`world are supported right now.

It would be really great if there would be some kind of interface for adding cli commands and options to `cds`, but as of now I think we need to have our own ones.

**Comment by gregorwolf** [comment]
Hi @mikezaschka I think we should update this issue with the possibilities of [cds-dbm](https://github.com/mikezaschka/cds-dbm) or?

**Comment by mikezaschka** [comment]
Because `cds` has no hooks, I needed to introduce a `cds-dbm` command which replaces the original one and offers the following options:

* `cds-dbm deploy` ([full documentation](https://github.com/mikezaschka/cds-dbm#deploy))
Deploys the CDS model to the PostgreSQL database. It has options to create a database (`--create-db`), load CSV data (`--load-via`) during deployment and automatically undeploy no more required tables (`--auto-undeploy`)

* `cds-dbm load` ([full documentation](https://github.com/mikezaschka/cds-dbm#load))
Explicitly loads CSV files to the database. It has a `--via` option, that can be either set to `full` (truncate a corresponding table first) or `delta`(keep the existing data and only insert new entries or update existing ones)

* `cds-dbm build` ([full documentation](https://github.com/mikezaschka/cds-dbm#build))
Generates build artifacts. Currently only SAP Cloud Platform Cloud Foundry is supported, which requires the following build-task-configuration:
```json
"build": {
    "tasks": [
    {
        "use": "postgres-cf",
        "src": "db",
        "options": {
        "deployCmd": "npx cds-dbm deploy --load-via delta --auto-undeploy"
        }
    }
    ]
}
```

* `cds-dbm diff` ([full documentation](https://github.com/mikezaschka/cds-dbm#diff))
Analyzes the current database schema and the CDS definition and shows a report of all differences.

* `cds-dbm drop` ([full documentation](https://github.com/mikezaschka/cds-dbm#drop))
Drops all tables and views of a CDS model from the database. If the `--all` parameter is given, then everything in the whole schema will be dropped, not only the CDS specific entities.

Some blogposts that show the usage of the commands:

* https://blogs.sap.com/2020/11/16/getting-started-with-cap-on-postgresql-node.js/
* https://blogs.sap.com/2020/11/30/run-and-deploy-cap-with-postgresql-on-sap-cloud-platform-cloud-foundry-node.js/

**Comment by mikezaschka** [comment]
If `cds` might open up one day in the future, we may get rid of `cds-dbm`. But for now, this is the way to go.
